# REQUIREMENTS =============================================================================================================

# in order for this docker-compose file to work you will require the following docker images
# - mysql:latest
# - php:8.2-apache
# These will be pulled automatically from dockerhub if you're connected to the internet
# and you're docker engine is running
# and you will require the following docker file which should be located relative to this file at
# ./bsu_api/Dockerfile

# -/bsu_warehouse_server
#         /- docker-compose.yaml
#         /- bsu_api/
#             /- Dockerfile
#             /- ...
#         /- bsu_frontend/
#             /- index.html
#             /- ...
#         /- bsu_database/
#             /- init.sql
#             /- ...

# finally run the command "docker-compose up" to start up  all  docker containers

# REQUIREMENTS =============================================================================================================

services:
  # MYSQL_DATABASE == is the name of the database notice how in the "bsu-api-server" container we
  # define the DATABASE_URL it contains the MYSQL_DATABASE at the end of the string
  # other environment variables include:
  # - MYSQL_ROOT_HOST which is set to '%' which means to allow connecting from any address
  # - MYSQL_ROOT_PASSWORD speaks for itself
  # - MYSQL_PASSWORD speaks for itself
  # - MYSQL_ROOT name of the root user (additional users are specified in the ./bsu_warehouse_database/init.sql file)
  bsu-db-server:
    image: mysql:latest
    container_name: bsu-db-server
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pwdAIteamDB_rootSUDOuser
      - MYSQL_PASSWORD=pwdAIteamDB
      - MYSQL_USER=aiUser
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=bsu_warehouse_db
    volumes:
      - ./bsu_database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
      interval: 5s
    # networks:
    #   - web

  # the DATABASE_URL environment variable is set so that if required we can load it in using the os.getenv("...") python function
  # right now we have set it manually in the "./bsu_api/config.py" file.
  # further on a volume is attached to the container which is mapped to the root folder of the ./genral_api_pefor enabling the --reload of the API server each time a change occures.
  # while this feature is good in developement to test out your API endpoints with a other service without having to reset your docker containers each time, it is NOT a good thing
  # in production.
  bsu-api-server:
    #image: sterren642/bsu-warehouse:api-latest
    image: ghcr.io/ai-practice-enterprice/bsu-warehouse:api-latest
    container_name: bsu-api-server
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./bsu_api:/app
    environment:
      - DATABASE_URL=mysql://aiUser:pwdAIteamDB@bsu-db-server:3306/bsu_warehouse_db
    depends_on:
      bsu-db-server:
        condition: service_healthy
    # networks:
    #   - web

  # we map a volume from our folder ./bsu_frontend to the /var/www/html folder because apache expects it to be there
  # see the docs
  bsu-website:
    #image: sterren642/bsu-warehouse:frontend-latest
    image: ghcr.io/ai-practice-enterprice/bsu-warehouse:frontend-latest
    container_name: bsu-website
    restart: unless-stopped
    volumes:
      - ./bsu_frontend:/var/www/html
    expose:
      - 80
    ports:
      - 8002:80
    # networks:
    #   - web

  # https://geshan.com.np/blog/2022/01/redis-docker/
  # https://www.ibm.com/think/topics/redis
  # https://zomro.com/blog/faq/301-kak-ustanovit-redis-v-docker
  # https://github.com/bitnami/containers/blob/main/bitnami/redis/README.md#customizable-environment-variables
  # !!! --requirepass pwdAIteamREDIScontainer only in developement otherwise => .env file
  bsu-redis:
    image: redis:latest
    container_name: bsu-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass pwdAIteamREDIScontainer
    environment:
      - REDIS_PASSWORD=pwdAIteamREDIScontainer
      - REDIS_PORT_NUMBER=6379
      - REDIS_DATABASE=0
    volumes:
      - ./bsu_redis:/data
    # networks:
    #   - web

  phpmyadmin:
    depends_on:
      - bsu-db-server
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      PMA_HOST: bsu-db-server
      PMA_PORT: 3306
    # networks:
    #   - web

# networks:
#   web:
