CREATE DATABASE IF NOT EXISTS bsu_warehouse_db;
CREATE USER 'aiUser'@'bsu-api-server' IDENTIFIED BY 'pwdAIteamDB';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'aiUser'@'bsu-api-server' WITH GRANT OPTION;
